# terminal prompt

format = """
[╭─░▒▓](#a3aed2)\
[ ](bg:#a3aed2 fg:#090c0c)\
[](bg:#6b90f6 fg:#a3aed2)\
$directory\
[](fg:#6b90f6 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#2a3047)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2a3047 bg:#1d2230)\
$time\
[](fg:#1d2230)\
\n$character"""

[character]
success_symbol = "╰─ "
error_symbol = "╰─ "
format = '[$symbol](fg:#a3aed2)'

[directory]
style = "fg:#e3e5e5 bg:#6b90f6"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#2a3047"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#2a3047)]($style)'

[rust]
symbol = ""
style = "bg:#2a3047"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#2a3047)]($style)'

[golang]
symbol = ""
style = "bg:#2a3047"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#2a3047)]($style)'

[php]
symbol = ""
style = "bg:#2a3047"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#2a3047)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
